"""
Slide builder: executes slide plans to produce the final PPTX file.
Simulates human editing by cloning template slides and replacing content.
"""

import copy
from pathlib import Path
from typing import Any, Callable

from pptx import Presentation
from pptx.util import Emu
from lxml import etree

from .text_editor import replace_span, set_paragraph_text
from .image_editor import insert_image, insert_image_into_placeholder, resize_image
from .validator import validate_page
from ..utils import get_logger

logger = get_logger(__name__)


def build_presentation(
    template_path: str | Path,
    slide_plan: dict[str, Any],
    template_schema: dict[str, Any],
    output_path: str | Path,
    progress_callback: Callable[[str], None] | None = None,
) -> Path:
    """
    Build the final presentation from a slide plan.

    Args:
        template_path: Path to the PPTX template file
        slide_plan: Plan generated by the LLM planner
        template_schema: Template schema from ppt_parser
        output_path: Where to save the output PPTX
        progress_callback: Optional callback for progress updates

    Returns:
        Path to the generated PPTX file
    """
    template_path = Path(template_path)
    output_path = Path(output_path)

    logger.info(f"Building presentation: {len(slide_plan.get('slides', []))} slides")

    # Load the template
    prs = Presentation(str(template_path))
    slide_width = prs.slide_width
    slide_height = prs.slide_height

    # Build layout group → representative slide index mapping
    layout_groups = {
        g["group_id"]: g for g in template_schema.get("layout_groups", [])
    }

    # Create new presentation with same dimensions
    new_prs = Presentation()
    new_prs.slide_width = slide_width
    new_prs.slide_height = slide_height

    # Copy slide master and layouts from template
    _copy_slide_master(prs, new_prs)

    total_slides = len(slide_plan.get("slides", []))
    all_issues = []

    for i, slide_spec in enumerate(slide_plan.get("slides", [])):
        if progress_callback:
            progress_callback(f"Building slide {i+1}/{total_slides}: {slide_spec.get('title', '')}")

        # Get template slide to clone
        group_id = slide_spec.get("layout_group_id", 0)
        group = layout_groups.get(group_id)

        if group is None:
            group = next(iter(layout_groups.values())) if layout_groups else None

        template_slide_idx = group["representative_index"] if group else 0
        template_slide_idx = min(template_slide_idx, len(prs.slides) - 1)

        # Clone and populate slide
        new_slide = _clone_slide(prs, new_prs, template_slide_idx)
        _populate_slide(new_slide, slide_spec, slide_width, slide_height)

        # Validate
        issues = validate_page(new_slide, i)
        all_issues.extend(issues)

        logger.debug(f"  Slide {i+1}: {slide_spec.get('title', '')} (layout group {group_id})")

    if all_issues:
        logger.warning(f"Validation found {len(all_issues)} issues")
        for issue in all_issues[:10]:
            logger.warning(f"  Slide {issue['slide']+1}: [{issue['severity']}] {issue['message']}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    new_prs.save(str(output_path))
    logger.info(f"Presentation saved: {output_path}")
    return output_path


def _clone_slide(source_prs: Presentation, target_prs: Presentation, slide_index: int):
    """
    Clone a slide from source presentation into target presentation.
    Copies XML content to preserve all visual styling.
    """
    source_slide = source_prs.slides[slide_index]

    # Add slide with matching layout
    # Find matching layout in target by name
    source_layout = source_slide.slide_layout
    target_layout = _find_matching_layout(target_prs, source_layout.name)

    if target_layout is None:
        target_layout = target_prs.slide_layouts[0]

    new_slide = target_prs.slides.add_slide(target_layout)

    # Copy the spTree (shape tree) from template slide
    source_sp_tree = source_slide.shapes._spTree
    target_sp_tree = new_slide.shapes._spTree

    # Remove auto-created shapes from new slide
    for child in list(target_sp_tree):
        target_sp_tree.remove(child)

    # Copy all elements from template
    for elem in source_sp_tree:
        target_sp_tree.append(copy.deepcopy(elem))

    # Copy slide background
    try:
        source_bg = source_slide.background._element
        new_bg = new_slide.background._element
        for child in list(new_bg):
            new_bg.remove(child)
        for child in source_bg:
            new_bg.append(copy.deepcopy(child))
    except Exception:
        pass

    return new_slide


def _find_title_placeholder(slide, ph_map: dict):
    """Return the title placeholder shape (CENTER_TITLE, TITLE type, or idx=0)."""
    for shape in slide.shapes:
        if shape.is_placeholder and shape.has_text_frame:
            ph_fmt = shape.placeholder_format
            if ph_fmt:
                try:
                    # PP_PLACEHOLDER.CENTER_TITLE=3, PP_PLACEHOLDER.TITLE=15 (int values)
                    if int(ph_fmt.type) in (3, 15):
                        return shape
                except Exception:
                    pass
    return ph_map.get(0)


def _populate_slide(
    slide,
    slide_spec: dict[str, Any],
    slide_width: int,
    slide_height: int,
) -> None:
    """Populate a slide with content from a slide spec."""
    content_blocks = slide_spec.get("content_blocks", [])

    # Build placeholder index → shape mapping
    ph_map = {}
    for shape in slide.shapes:
        if shape.is_placeholder:
            ph_format = shape.placeholder_format
            if ph_format:
                ph_map[ph_format.idx] = shape

    # Clear ALL text placeholders first — removes "First bullet point..." template text
    for shape in ph_map.values():
        if shape.has_text_frame:
            replace_span(shape, "")

    # Always force-set the title from slide_spec["title"] so every slide has unique text.
    # Only skip if a content_block explicitly targets this same placeholder.
    title_text = slide_spec.get("title", "")
    blocks_ph_idxs = {b.get("placeholder_idx") for b in content_blocks}
    if title_text:
        title_shape = _find_title_placeholder(slide, ph_map)
        if title_shape is not None:
            title_idx = title_shape.placeholder_format.idx if title_shape.placeholder_format else 0
            if title_idx not in blocks_ph_idxs and title_shape.has_text_frame:
                replace_span(title_shape, title_text)

    for block in content_blocks:
        ph_idx = block.get("placeholder_idx", 0)
        content_type = block.get("content_type", "text")
        shape = ph_map.get(ph_idx)

        if shape is None:
            logger.debug(f"Placeholder idx={ph_idx} not found on slide")
            continue

        if content_type == "title":
            text = block.get("text", "")
            if text and shape.has_text_frame:
                replace_span(shape, text)

        elif content_type == "text":
            text = block.get("text", "")
            if text and shape.has_text_frame:
                replace_span(shape, text)

        elif content_type == "bullet_list":
            bullets = block.get("bullet_points", [])
            if bullets and shape.has_text_frame:
                set_paragraph_text(shape, bullets, is_bullet_list=True)

        elif content_type == "image":
            image_path = block.get("image_path", "")
            if image_path:
                image_path_obj = Path(image_path)
                if image_path_obj.exists():
                    # Try placeholder insertion first
                    ph_type = shape.placeholder_format.type if shape.placeholder_format else 0
                    if ph_type == 18:  # PICTURE
                        insert_image_into_placeholder(shape, image_path_obj)
                    else:
                        # Insert at placeholder position
                        insert_image(
                            slide,
                            image_path_obj,
                            left=shape.left / slide_width,
                            top=shape.top / slide_height,
                            width=shape.width / slide_width,
                            height=shape.height / slide_height,
                            slide_width_emu=slide_width,
                            slide_height_emu=slide_height,
                        )

    # Add speaker notes if provided
    notes_text = slide_spec.get("speaker_notes", "")
    if notes_text:
        _set_speaker_notes(slide, notes_text)


def _set_speaker_notes(slide, notes_text: str) -> None:
    """Set speaker notes on a slide."""
    try:
        notes_slide = slide.notes_slide
        tf = notes_slide.notes_text_frame
        tf.text = notes_text
    except Exception as e:
        logger.debug(f"Could not set speaker notes: {e}")


def _find_matching_layout(prs: Presentation, layout_name: str):
    """Find a slide layout by name in the presentation."""
    for layout in prs.slide_layouts:
        if layout.name == layout_name:
            return layout
    return None


def _copy_slide_master(source_prs: Presentation, target_prs: Presentation) -> None:
    """
    Copy slide master and layouts from source to target presentation.
    This preserves the visual theme of the template.
    """
    try:
        from pptx.oxml.ns import qn

        # Copy the slide master XML
        source_master = source_prs.slide_master
        target_master = target_prs.slide_master

        # Copy master element content
        source_master_elem = source_master._element
        target_master_elem = target_master._element

        # Replace cSld (common slide data = shapes/background)
        src_cSld = source_master_elem.find(qn("p:cSld"))
        tgt_cSld = target_master_elem.find(qn("p:cSld"))

        if src_cSld is not None and tgt_cSld is not None:
            target_master_elem.replace(tgt_cSld, copy.deepcopy(src_cSld))

        # Copy theme colors
        src_theme = source_master_elem.find(qn("p:txStyles"))
        if src_theme is not None:
            tgt_theme = target_master_elem.find(qn("p:txStyles"))
            if tgt_theme is not None:
                target_master_elem.replace(tgt_theme, copy.deepcopy(src_theme))

        # Copy slide layouts
        for layout in source_prs.slide_layouts:
            try:
                # Add new layout to target master
                target_master.slide_layouts._sldLayoutIdLst.append(
                    copy.deepcopy(layout._element)
                )
            except Exception:
                pass

    except Exception as e:
        logger.debug(f"Partial slide master copy (non-critical): {e}")


class SlideBuilder:
    """High-level interface for building presentations."""

    def __init__(
        self,
        template_path: str | Path,
        template_schema: dict[str, Any],
    ) -> None:
        self.template_path = Path(template_path)
        self.template_schema = template_schema

    def build(
        self,
        slide_plan: dict[str, Any],
        output_path: str | Path,
        progress_callback: Callable[[str], None] | None = None,
    ) -> Path:
        """Build the presentation and return the output path."""
        return build_presentation(
            self.template_path,
            slide_plan,
            self.template_schema,
            output_path,
            progress_callback,
        )
